"""testeando app

Revision ID: 304242cb52d6
Revises: 
Create Date: 2025-06-26 17:18:47.164204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304242cb52d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pais_id'), 'pais', ['id'], unique=False)
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincia_id'), 'provincia', ['id'], unique=False)
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudad_id'), 'ciudad', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('deposito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposito_id'), 'deposito', ['id'], unique=False)
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedor_id'), 'proveedor', ['id'], unique=False)
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursal_id'), 'sucursal', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('precioCompra', sa.Float(), nullable=False),
    sa.Column('precioVenta', sa.Float(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('remito_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_deposito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_deposito'], ['deposito.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remito_compra_id'), 'remito_compra', ['id'], unique=False)
    op.create_table('remito_devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remito_devolucion_id'), 'remito_devolucion', ['id'], unique=False)
    op.create_table('remito_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('origen', sa.VARCHAR(), nullable=False),
    sa.Column('destino', sa.VARCHAR(), nullable=False),
    sa.Column('id_deposito', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_deposito'], ['deposito.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remito_transferencia_id'), 'remito_transferencia', ['id'], unique=False)
    op.create_table('remito_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remito_venta_id'), 'remito_venta', ['id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_sucursal', sa.Integer(), nullable=True),
    sa.Column('cantidad_deposito', sa.Integer(), nullable=True),
    sa.Column('id_deposito', sa.Integer(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_deposito'], ['deposito.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_remito_venta_id'), table_name='remito_venta')
    op.drop_table('remito_venta')
    op.drop_index(op.f('ix_remito_transferencia_id'), table_name='remito_transferencia')
    op.drop_table('remito_transferencia')
    op.drop_index(op.f('ix_remito_devolucion_id'), table_name='remito_devolucion')
    op.drop_table('remito_devolucion')
    op.drop_index(op.f('ix_remito_compra_id'), table_name='remito_compra')
    op.drop_table('remito_compra')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_sucursal_id'), table_name='sucursal')
    op.drop_table('sucursal')
    op.drop_index(op.f('ix_proveedor_id'), table_name='proveedor')
    op.drop_table('proveedor')
    op.drop_index(op.f('ix_deposito_id'), table_name='deposito')
    op.drop_table('deposito')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_ciudad_id'), table_name='ciudad')
    op.drop_table('ciudad')
    op.drop_index(op.f('ix_provincia_id'), table_name='provincia')
    op.drop_table('provincia')
    op.drop_index(op.f('ix_pais_id'), table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
