"""reestructuracion de carpetas

Revision ID: 55e9b05d708e
Revises: 
Create Date: 2025-05-30 00:02:56.548813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e9b05d708e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pais_id'), 'pais', ['id'], unique=False)
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincia_id'), 'provincia', ['id'], unique=False)
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudad_id'), 'ciudad', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_ciudad_id'), table_name='ciudad')
    op.drop_table('ciudad')
    op.drop_index(op.f('ix_provincia_id'), table_name='provincia')
    op.drop_table('provincia')
    op.drop_index(op.f('ix_pais_id'), table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
