"""agregado de campos de cliente

Revision ID: d660a64aa3e8
Revises: f93355b3d6bd
Create Date: 2025-05-23 21:26:28.178070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd660a64aa3e8'
down_revision: Union[str, None] = 'f93355b3d6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('telefono', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('email', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('direccion', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('id_ciudad', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'id_ciudad')
    op.drop_column('cliente', 'direccion')
    op.drop_column('cliente', 'email')
    op.drop_column('cliente', 'telefono')
    # ### end Alembic commands ###
