name: "Render Keep Alive Ping"

on:
  schedule:
    - cron: '*/10 * * * *' 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer Ping al Endpoint de Render
        run: |
          curl -s --head "https://stocky-backend-crqm.onrender.com/"